services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StudioMitte\FriendlyCaptcha\:
    resource: '../Classes/*'

  StudioMitte\FriendlyCaptcha\Service\Api:
    public: true

  StudioMitte\FriendlyCaptcha\ConfigurationInterface:
    alias: StudioMitte\FriendlyCaptcha\Configuration
    public: true
